name: mojophysio
favicon: null
layout_spectrum: 0.44498161878436804
typography_spectrum: 0.9842840326018631
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7529652521479875
  lightness: 0.14328101254068315
  saturation: 0.5460874948184937
  rhythmicContrast: 0.8896359282080084
purpose: []
