name: mojophysio
favicon: null
layout_spectrum: 0.99105
typography_spectrum: 0.88619
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffe'
    - '#737888'
    - '#b5c1cc'
    - '#261609'
    - '#db2530'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
