title: MOJOPhysio&Yoga
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.125
  brandStrength: 1
  lightness: 0.375
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#4D4D4D'
    - '#AB936F'
    - '#D71F2A'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: mojophysio
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1459888
layout_spectrum: 0.7364739
